package starter.settings.data;

public class Data extends SetJSON {

    private static final String AUTO = "autogenerateData";

    public Boolean getAutogenerateDataOption() {
        return getRootJSONData(AUTO);
    }
}
